Repository nswallet-official/nswallet, pull requests merged in 2020-03, with the labels that each got.

#10 [UPDATE] New link to banner
  README.md
Labels: documentation

#12 addinkg links to readme, adapt to iOS policy
  .sonarcloud.properties
  README.md
  src/NSWallet/NSWallet.NetStandard/Views/LoginScreen/InfoView.cs
  src/NSWallet/NSWallet.NetStandard/Views/LoginScreen/LoginScreenView.cs
Labels: enhancement

#14 [UPDATE] CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#24 [FIX] Auto-backups
  src/NSWallet/Droid/NSWallet.Droid.csproj
  src/NSWallet/NSWallet.NetStandard/Helpers/Settings.cs
  src/NSWallet/NSWallet.NetStandard/NSWallet.cs
Labels: bug

#23 [ADD] EditorConfig
  .editorconfig
Labels: enhancement

#26 [FEATURE] Test coverage
  README.md
  src/NSWallet/NSWallet.UnitTests/BusinessFixture.cs
  src/NSWallet/NSWallet.UnitTests/Helpers/Language.cs
  src/NSWallet/NSWallet.UnitTests/Localization/LocalizationFixture.cs
  src/NSWallet/NSWallet.UnitTests/NSWallet.UnitTests.csproj
  src/NSWallet/NSWallet.UnitTests/Resources/ResourcesFixture.cs
  src/NSWallet/NSWallet.UnitTests/TestData/Backups/nswallet_from_future.zip
  src/NSWallet/NSWallet.UnitTests/TestData/Backups/nswallet_old.zip
  src/NSWallet/NSWallet.UnitTests/packages.config
  src/NSWallet/NSWallet.sln
  src/NSWallet/coverlet.runsettings
Labels: enhancement

#30 [UPDATE] Repository graphics
  README.md
  graphics/badge-xamarin.svg
  graphics/banner.png
Labels: documentation

#34 [UPDATE] Renamed NetStandard project
  src/NSWallet/Droid/NSWallet.Droid.csproj
  src/NSWallet/NSWallet.Mac/NSWallet.Mac.csproj
  src/NSWallet/NSWallet.NetStandard/NSWallet.cs
  src/NSWallet/NSWallet.NetStandard/NSWallet.csproj
  src/NSWallet/NSWallet.UnitTests/BusinessFixture.cs
  src/NSWallet/NSWallet.UnitTests/Localization/LocalizationFixture.cs
  src/NSWallet/NSWallet.UnitTests/NSWallet.UnitTests.csproj
  src/NSWallet/NSWallet.UnitTests/Resources/ResourcesFixture.cs
  src/NSWallet/NSWallet.sln
  src/NSWallet/iOS/NSWallet.iOS.csproj
Labels: refactoring, update

#35 [UPDATE] Contributing
  .github/CONTRIBUTING.md
Labels: repo, update

#36 [ADD] Codecov configuration
  codecov.yml
Labels: unit-tests
